module.exports = [
  'It is not the mountain we conquer but ourselves.',
  'Win on Sunday, sell on Monday.',
  'I do not fear computers. I fear lack of them.',
  'Standards are always out of date.',
  'Real knowledge is to know the extent of one\'s ignorance.',
  'Stop optimizing for programmers and start optimizing for users.',
  'Low level programming is good for the programmer\'s soul.',
  'Before software should be reusable, it should be usable.',
  'The best way to predict the future is to implement it.',
  'The only truly secure system is one that is powered off.',
  'The smarter you get, the less you speak.',
  'Compliment people, magnify their strengths.',
  'I have failed over and over again, that is why I succeed.',
  'Be strong in body, clean in mind, lofty in ideals.',
  'You dare bring light to my lair? You must die.',
  'Wake from your sleep. The drying of your tears.',
  'Sing us a song to keep us warm.',
  'Impulsive thinker, compulsive drinker, addict.',
  'Quit tryna bite me and pinch, you wench, sit still.',
  'I heard your voice through a photograph.',
  'Stranger things could never change my mind.',
  'The ashtray\'s full and I\'m spillin\' my guts.',
  'I walk a lonely road, the only one that I have ever known.',
  'The more you know, the more you realize you know nothing.',
  'Attitude is a little thing that makes a big difference.',
  'An optimist sees the opportunity in every difficulty.',
  'Kites rise highest against the wind, not with it.',
  'A heart that\'s full up like a landfill.',
  'With your opinion which is of no consequence at all.',
  'You watch your feet for cracks in the pavement.',
  'I wish that they\'d swoop down in a country lane.',
  'They were perfectly normal, thank you very much.',
  'You\'re a little scary sometimes, you know that?',
  'We could all have been killed, or worse, expelled.',
  'I solemnly swear I am up to no good.',
  'Take a good look at how he treats his inferiors.',
  'Do one thing every day that scares you.',
  'Time to test our talents in the real world.',
  'Words are our most inexhaustible source of magic.',
  'One can never have enough socks.',
  'Recognize that it matters not what someone is born.',
  'Adding power makes you faster on the straights.',
  'Subtracting weight makes you faster everywhere.',
  'Injustice anywhere is a threat to justice everywhere.',
  'Hate is too great a burden to bear.',
  'What makes horse racing and missionaries.',
  'Design is intelligence made visible.',
  'Every great design begins with an even better story.',
  'Catch me by the Clair, I\'ll be right there.',
  'Doors wide, my trunk bump like Eddy Road.',
  'General Tso, half a dozen on the stick.',
  'There\'s a man riding a horse on top of my chest.',
  'Skateboarders grind, I grind too.',
  'I drive a Chevrolet movie theater.',
  'No one knows what I do, but I look pretty cool.',
  'I\'m a squirrel, lookin\' for my next nut.',
  'I have seen rings of smoke through the trees.',
  'We\'re not making music for aliens here.',
  'If you automate a mess, you get an automated mess.',
  'Simplicity, carried to the extreme, becomes elegance.',
  'Old age should burn and rave at close of day.',
  'Wild men who caught and sang the sun in flight.',
  'Artificial amateurs, aren\'t at all amazing.',
  'Broken barriers bounded by the bomb beat.',
  'Canceling cats, got they canopies collapsing.',
  'Flurries of funk felt, feeding the fanatics.',
  'Gift got great, global goods gone glorious.',
  'In an instant, I\'ll rise in an irate state.',
  'Justly, it\'s just me, writing my journals.',
  'Karate kick type Brits in my kingdom.',
  'Let me live a long life, lyrically lessons is.',
  'Marvel and move, many mock what I\'ve mastered.',
  'Knack, never lack, make noise nationally.',
  'Out of sight, out of mind, wide beaming opticals.',
  'Pummeling petty powder puffs in my prime.',
  'Really raw raps, risin\' up rapidly.',
  'Silencing super fire saps that are soft.',
  'Universal, unique, untouched, the raw uncut.',
  'Violate vibes that are vain make \'em vanish.',
  'Zero in, zen thoughts, overzealous rhyme.',
  'We have guided missiles and misguided men.',
  'A genuine leader is not a searcher for consensus.',
  'Accept finite disappointment but never lose infinite hope.',
  'Live together as brothers or perish together as fools.',
  'No person has the right to rain on your dreams.',
  'An eye for an eye leaves everybody blind.',
  'There\'s a jungle cat in the bathroom.',
  'Allen, did you just eat sofa pizza?',
  'That rug really tied the room together.',
  'Zen and the art of motorcycle maintenance.',
  'It accomplishes nothing, but everyone keeps using it.',
  'This is a very complicated case, Maude.',
  'Obviously, you\'re not a golfer.',
  'Dropping in coming through the mesh.',
  'Hard to leave when it\'s picturesque.',
  'This aggression will not stand, man.',
  'Get off the high road, Summer.',
  'Glowing rocks in the kitchen trash.',
  'The only species on earth that observes shark week.',
  'Put it in a letter, Jane Austen.',
  'That was a game. This is paintball.',
  'In Espanol, my nickname is El Tigre Chino.',
  'I got a penthouse on both coasts, ph balance.',
  'We\'re all kind of crazytown bananapants.',
  'I wanna see if wiener dogs are born that way.',
  'The crossing guards used to lure me into traffic.',
  'And you could have it all, my empire of dirt.',
  'It\'s called chemistry, I have it with everybody.',
  'I don\'t have an ego. My Facebook photo is a landscape.',
  'Some flies are too awesome for the wall.',
]